#!/bin/zsh

alias vim="nvim"
alias vi="nvim"
alias zshrc="nvim ~/.zshrc"
alias szshrc="source ~/.zshrc"
alias cloud="ssh -t CLOUD"
alias lighthouse_hk="ssh -t LIGHTHOUSE_HK"
alias lighthouse_jp="ssh -t LIGHTHOUSE_JP"
alias awdl_off="sudo ifconfig awdl0 down"
alias awdl_on="sudo ifconfig awdl0 up"
