#!/bin/zsh

alias vim="nvim"
alias vi="nvim"
alias zshrc="nvim ~/.zshrc"
alias szshrc="source ~/.zshrc"
alias copydiff="git diff --staged ':(exclude)pnpm-lock.yaml' | pbcopy"
alias awdl_off="sudo ifconfig awdl0 down"
alias awdl_on="sudo ifconfig awdl0 up"
alias rm_duplicates_open_with="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user"
