# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$ZSH/custom
export ZSH_THEME="powerlevel10k/powerlevel10k"
export PATH="/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/opt/homebrew/bin:$HOME/bin"
export PATH="/opt/homebrew/opt/ruby/bin:$PATH"
export CONFIG_DIR=$HOME/Workspace/Github/dotfiles/config
export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"

# zsh-completion
fpath+="$ZSH_CUSTOM/plugins/zsh-completions/src"

[[ -f /opt/homebrew/etc/profile.d/autojump.sh ]] && . /opt/homebrew/etc/profile.d/autojump.sh

plugins=(
  git
  autojump
  macos
  zsh-syntax-highlighting
  zsh-autosuggestions
)

source "$CONFIG_DIR/aliases"

[[ ! -f "$CONFIG_DIR/aliases-work" ]] || source "$CONFIG_DIR/aliases-work"
[[ ! -f "$CONFIG_DIR/tokens" ]] || source "$CONFIG_DIR/tokens"

source "$ZSH/oh-my-zsh.sh"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# ollama
export OLLAMA_NUM_PARALLEL=2
export OLLAMA_MAX_LOADED_MODELS=2
export OLLAMA_ORIGINS=moz-extension://*,chrome-extension://*,safari-web-extension://*
export OLLAMA_HOST=0.0.0.0

# bun completions
[[ -s "$HOME/.bun/_bun" ]] && source "$HOME/.bun/_bun"

unset ZSH_AUTOSUGGEST_USE_ASYNC

# Windsurf
export PATH="$HOME/.codeium/windsurf/bin:$PATH"

# uv: python package manager
eval "$(uv generate-shell-completion zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
